# Generated by Django 3.0.1 on 2020-01-03 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('arrival_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField(blank=True)),
            ],
        ),
    ]
