# Generated by Django 3.0.1 on 2020-01-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single_room', 'single_room'), ('double_room', 'double_room'), ('executive_room', 'executive_room')], default=('double_room', 'double_room'), max_length=30),
        ),
    ]
