# Generated by Django 3.0.1 on 2020-02-13 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200107_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('single_room', 'Single Room'), ('double_room', 'Double Room'), ('executive_room', 'Executive Room')], default=('double_room', 'Double Room'), max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2020, 2, 15, 20, 7, 4, 247628, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
