# Generated by Django 3.0.3 on 2020-02-21 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200213_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='info@technocrats.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(default='Guest', max_length=120),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2020, 2, 23, 16, 2, 57, 745341, tzinfo=utc)),
        ),
    ]
